theme: jekyll-theme-slate
title: "Trans Voice Notes"
description: "My trans voice notes (for MTF/transfeminine) in markdown. I made this repo, so I have an easy place to read these notes and keep them somewhere safe just in case the originals version of them going missing/down "
author: "CutThroat78"
show_downloads: false
github:
   is_project_page: false
